DROP TABLE LISTEDON;
DROP TABLE STOCKINFO;
DROP TABLE ACQUIREDCOMPANY;
DROP TABLE STOCKEXCHANGE;
DROP TABLE FIRMS;
DROP TABLE REVENUE;
DROP TABLE FINANCES;
DROP TABLE EARNINGS;
DROP TABLE LIABILITIES;
DROP TABLE FOUNDER;
DROP TABLE INVESTS;
DROP TABLE ACTIVEIN;
DROP TABLE INDUSTRY;
DROP TABLE INVESTOR;
DROP TABLE COMPANY;
DROP TABLE COUNTRY;
DROP TABLE LANGUAGE;
DROP TABLE CULTURE;
DROP TABLE LVSTOUA;
DROP TABLE MVFTOIVCPD;
DROP TABLE CEO;
DROP TABLE EDUCATION;




